# Change these first
owner: Nexaorion
repo: status-page

sites:
  - name: Auth Gateway
    url: https://auth.nexaorion.cn/demo-app
  - name: IAM System
    url: https://sso.nexaorion.tech
  - name: Mail Server
    url: https://mail.nexaorion.tech
  - name: WAF
    url: https://iam-waf.nexaorion.tech
  - name: Docs
    url: https://docs.lanko.space

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.nexaorion.tech
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Nexaorion Status
  introTitle: "nexaorion's Status Page"
  navbar:
    - title: Status
      href: /

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
